{{- if .Values.collector.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "jaeger.collector.name" . }}
  labels:
    app: {{ template "jaeger.name" . }}
    jaeger-infra: collector-deployment
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: collector
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.collector.annotations }}
  annotations:
{{ toYaml .Values.collector.annotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.collector.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
{{- if .Values.collector.podAnnotations }}
      annotations:
{{ toYaml .Values.collector.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app: {{ template "jaeger.name" . }}
        component: collector
        release: {{ .Release.Name }}
        jaeger-infra: collector-pod
{{- if .Values.collector.podLabels }}
{{ toYaml .Values.collector.podLabels | indent 8 }}
{{- end }}
    spec:
      nodeSelector:
{{ toYaml .Values.collector.nodeSelector | indent 8 }}
{{- if .Values.collector.tolerations }}
      tolerations:
{{ toYaml .Values.collector.tolerations | indent 8 }}
{{- end }}
      containers:
      - name: {{ template "jaeger.collector.name" . }}
        image: "{{ .Values.global.hub }}/{{ .Values.collector.image }}:{{ .Values.collector.tag }}"
        {{- if eq .Values.storage.type "aliyun-log" }}
        args:
        - /go/bin/collector-linux
        - --collector.zipkin.http-port=9411
        - --aliyun-log.project=$(ALIYUN_SLS_PROJECT)
        - --aliyun-log.endpoint=$(ALIYUN_SLS_ENDPOINT)
        - --aliyun-log.access-key-id=$(ACCESS_KEY_ID)
        - --aliyun-log.access-key-secret=$(ACCESS_KEY_SECRET)
        - --aliyun-log.span-logstore=$(ALIYUN_SLS_LOGSTORE)
        - --aliyun-log.alicloud-k8s-flag=true
        {{- end }}
        imagePullPolicy: {{ .Values.collector.pullPolicy }}
        env:
          {{- range $key, $value := .Values.collector.cmdlineParams }}
          - name: {{ $key | replace "." "_" | replace "-" "_" | upper | quote }}
            value: {{ $value | quote }}
          {{- end }}
          - name: SPAN_STORAGE_TYPE
            valueFrom:
              configMapKeyRef:
                name: {{ template "jaeger.fullname" . }}
                key: span-storage.type
          {{- if eq .Values.storage.type "aliyun-log" }}
          - name: ALIYUN_SLS_PROJECT
            valueFrom:
              configMapKeyRef:
                name: {{ template "jaeger.fullname" . }}
                key: aliyun-sls.project
          - name: ALIYUN_SLS_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: {{ template "jaeger.fullname" . }}
                key: aliyun-sls.endpoint
          - name: ALIYUN_SLS_LOGSTORE
            valueFrom:
              configMapKeyRef:
                name: {{ template "jaeger.fullname" . }}
                key: aliyun-sls.logstore
          {{- end }}
          {{- if eq .Values.storage.type "cassandra" }}
          - name: CASSANDRA_SERVERS
            valueFrom:
              configMapKeyRef:
                name: {{ template "jaeger.fullname" . }}
                key: cassandra.servers
          - name: CASSANDRA_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ template "jaeger.fullname" . }}
                key: cassandra.port
          - name: CASSANDRA_KEYSPACE
            valueFrom:
              configMapKeyRef:
                name: {{ template "jaeger.fullname" . }}
                key: cassandra.keyspace
          {{- end }}
          {{- if eq .Values.storage.type "elasticsearch" }}
          - name: ES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ template "jaeger.fullname" . }}
                key: es.password
          - name: ES_SERVER_URLS
            valueFrom:
              configMapKeyRef:
                name: {{ template "jaeger.fullname" . }}
                key: es.server-urls
          - name: ES_USERNAME
            valueFrom:
              configMapKeyRef:
                name: {{ template "jaeger.fullname" . }}
                key: es.username
          {{- end }}
          - name: COLLECTOR_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ template "jaeger.fullname" . }}
                key: collector.port
          - name: COLLECTOR_HTTP_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ template "jaeger.fullname" . }}
                key: collector.http-port
          - name: COLLECTOR_ZIPKIN_HTTP_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ template "jaeger.fullname" . }}
                key: collector.zipkin.http-port
        ports:
        - containerPort: {{ .Values.collector.service.tchannelPort }}
          name: tchannel
          protocol: TCP
        - containerPort: {{ .Values.collector.service.httpPort }}
          name: http
          protocol: TCP
        - containerPort: {{ .Values.collector.service.healthCheckPort }}
          name: healthcheck
          protocol: TCP
        - containerPort: {{ .Values.collector.service.zipkinPort }}
          name: zipkin
          protocol: TCP
        readinessProbe:
          httpGet:
            port: healthcheck
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            port: healthcheck
          initialDelaySeconds: 10
        resources:
{{ toYaml .Values.collector.resources | indent 10 }}
      dnsPolicy: {{ .Values.collector.dnsPolicy }}
      restartPolicy: Always
{{- end -}}
