apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jaeger.fullname" . }}
  labels:
    app: {{ template "jaeger.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.storage.aliyun_sls.accesskey.id }}
  aliyun-sls.accesskey.id:  {{ .Values.storage.aliyun_sls.accesskey.id | b64enc | quote }}
  {{ end }}
  {{ if .Values.storage.aliyun_sls.accesskey.secret }}
  aliyun-sls.accesskey.secret:  {{ .Values.storage.aliyun_sls.accesskey.secret | b64enc | quote }}
  {{ end }}
