apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jaeger.fullname" . }}
  labels:
    app: {{ template "jaeger.name" . }}
    jaeger-infra: common-configmap
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  collector.host-port: {{ template "jaeger.collector.host-port" . }}
  collector.http-port: {{ .Values.collector.service.httpPort | quote }}
  collector.port: {{ .Values.collector.service.tchannelPort | quote }}
  collector.zipkin.http-port: {{ .Values.collector.service.zipkinPort | quote }}
   
  hotrod.agent-host-port: "{{ template "jaeger.hotrod.tracing.host" . }}:{{ .Values.hotrod.tracing.port }}"
  span-storage.type: {{ .Values.storage.type | quote }}
  query.health-check-http-port: {{ .Values.query.healthCheckPort | quote }}
  query.port: {{ .Values.query.service.targetPort | quote }}

  # aliyun sls
  aliyun-sls.project: {{ .Values.storage.aliyun_sls.project | quote }}
  aliyun-sls.endpoint: {{ .Values.storage.aliyun_sls.endpoint | quote }}
  aliyun-sls.logstore: {{ .Values.storage.aliyun_sls.logstore | quote }}

  # cassandra.archive.connections-per-host:
  # cassandra.archive.keyspace:
  # cassandra.archive.max-retry-attempts:
  # cassandra.archive.password:
  # cassandra.archive.port:
  # cassandra.archive.proto-version:
  # cassandra.archive.servers:
  # cassandra.archive.socket-keep-alive:
  # cassandra.archive.timeout:
  # cassandra.archive.username:
  # cassandra.connections-per-host:
  # cassandra.max-retry-attempts:
  # cassandra.password:
  # cassandra.proto-version:
  # cassandra.socket-keep-alive:
  # cassandra.timeout:
  # cassandra.username:
  # collector.health-check-http-port:
  # collector.num-workers:
  # collector.queue-size:
  # collector.write-cache-ttl:
  # dependency-storage.data-frequency:
  # discovery.min-peers:
  # es.archive.max-span-age:
  # es.archive.num-replicas:
  # es.archive.num-shards:
  # es.archive.password:
  # es.archive.server-urls:
  # es.archive.sniffer:
  # es.archive.username:
  # es.max-span-age:
  # es.num-replicas:
  # es.num-shards:
  # es.sniffer:
  # http-server.host-port:
  # log-level:
  # metrics-backend:
  # metrics-http-route:
  # processor.jaeger-binary.server-host-port:
  # processor.jaeger-binary.server-max-packet-size:
  # processor.jaeger-binary.server-queue-size:
  # processor.jaeger-binary.workers:
  # processor.jaeger-compact.server-host-port:
  # processor.jaeger-compact.server-max-packet-size:
  # processor.jaeger-compact.server-queue-size:
  # processor.jaeger-compact.workers:
  # processor.zipkin-compact.server-host-port:
  # processor.zipkin-compact.server-max-packet-size:
  # processor.zipkin-compact.server-queue-size:
  # processor.zipkin-compact.workers:
  # query.prefix:
  # query.static-files:
  # query.ui-config:
