apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  type: ClusterIP
  ports:
  - name: "zipkin-rest"
    port: 9411
    targetPort: 9411
  selector:
    app: {{ template "jaeger.name" . }}
    component: collector
    release: {{ .Release.Name }}
    jaeger-infra: collector-pod