---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: axd-mq-server
  generation: 1
  labels:
    app: axd-mq-server
    version: v3
  servicename: axd-mq-server
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: axd-mq-server
  serviceName: axd-mq-server
  template:
    metadata:
      labels:
        app: axd-mq-server
        version: v3
    spec:
      containers:
        - env:
            - name: RABBITMQ_LOGS
              value: '-'
            - name: RABBITMQ_SASL_LOGS
              value: '-'
            - name: RABBITMQ_GPG_KEY
              value: 0A9AF2115F4687BD29803A206B73A36E6026DFCA
            - name: RABBITMQ_GITHUB_TAG
              value: v3.7.8
            - name: LANG
              value: C.UTF-8
            - name: HOME
              value: /var/lib/rabbitmq
            - name: RABBITMQ_DEFAULT_USER
              value: axd
            - name: RABBITMQ_DEFAULT_PASS
              value: axd@rabbitmq
          image: 'registry-vpc.cn-shenzhen.aliyuncs.com/axd/rabbitmq:3-management'
          imagePullPolicy: IfNotPresent
          name: axd-mq-server
          ports:
            - containerPort: 15672
              protocol: TCP
            - containerPort: 25672
              protocol: TCP
            - containerPort: 4369
              protocol: TCP
            - containerPort: 5671
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: axd-mq-server
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - flexVolume:
          driver: alicloud/disk
          fsType: ext4
          options:
            volumeId: d-wz9en8h1q14kagbjnq2h
        name: axd-mq-server
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
