apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    app: kiali
data:
  config.yaml: |
    server:
      port: 20001
    external_services:
      jaeger:
        url: {{ .Values.dashboard.jaegerURL }}
      grafana:
        url: "http://prometheus.{{ .Release.Namespace }}:9090"
