apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "xxl-job.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "xxl-job.name" . }}
    helm.sh/chart: {{ include "xxl-job.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "xxl-job.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "xxl-job.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - java
          - -jar
          - -Dspring.datasource.url=jdbc:mysql://rm-t4n22293kwn7is256.mysql.singapore.rds.aliyuncs.com:3306/xxl-job?Unicode=true&characterEncoding=UTF-8
          - -Dspring.datasource.username=xxljob
          - -Dspring.datasource.password=G4XYBKC123!
          - /app.jar
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
