# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: registry-vpc.ap-southeast-1.aliyuncs.com/ccfox/configserver
  tag: 1.5.13
  pullPolicy: Always

service:
  enabled: true
  type: LoadBalancer
  externalPort: 8888
  internalPort: 8888

global:
  rabbitmq:
    url:
    host: 
    port: 5672
    username: user
    password: 
    virtualHost:
    sslEnabled: false
  
  eureka:
    service:
      name: newcoin-discovery-server-ack-springcloud-eureka-0
      port: 8761

management:
  contextPath: /admin
  security:
    enabled: false
    role: 
      
security:
  user:
    name: 
    password: 


affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: evn
          operator: In
          values:
          - test

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://newcoin-discovery-server-ack-springcloud-eureka-svc-0:8761/eureka
spring:
  cloud:
    bus:
      enabled: false
    config:
      server:
        git:
          uri: https://gitlab.coinidx.pro/exchange/newcoin-config-repo-ccfox.git
          label: pro
          profile: pro
          searchPaths:
          username: ccfoxops
          password: 6ggRXd6bFVTSNBdjV7Kt


bootstrap:
  values: 



