{{- if .Values.runMigrations }}
# Why is this Job duplicated and not using only helm hooks?
# See: https://github.com/helm/charts/pull/7362
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "kong.fullname" . }}-pre-upgrade-migrations
  labels:
    app: {{ template "kong.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: pre-upgrade-migrations
  annotations:
    helm.sh/hook: "pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  template:
    metadata:
      name: {{ template "kong.name" . }}-pre-upgrade-migrations
      labels:
        app: {{ template "kong.name" . }}
        release: "{{ .Release.Name }}"
        component: pre-upgrade-migrations
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      initContainers:
      - name: wait-for-postgres
        image: busybox
        env:
        - name: KONG_PG_HOST
          valueFrom:
            secretKeyRef:
              name: kongsecret
              key: hostname
        - name: KONG_PG_PORT
          value: "3433"
        - name : KONG_PG_DATABASE
          value: "kong"
        - name: KONG_PG_USER
          valueFrom:
            secretKeyRef:
              name: kongsecret
              key: username
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kongsecret
              key: password
        command: [ "/bin/sh", "-c", "until nc -zv $KONG_PG_HOST $KONG_PG_PORT -w1; do echo 'waiting for db'; sleep 1; done" ]
      containers:
      - name: {{ template "kong.name" . }}-upgrade-migrations
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: KONG_NGINX_DAEMON
          value: "off"
        {{- include "kong.env" .  | indent 8 }}
        - name: KONG_PG_HOST
          valueFrom:
            secretKeyRef:
              name: kongsecret
              key: hostname
        - name: KONG_PG_PORT
          value: "3433"
        - name : KONG_PG_DATABASE
          value: "kong"
        - name: KONG_PG_USER
          valueFrom:
            secretKeyRef:
              name: kongsecret
              key: username
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kongsecret
              key: password
        {{- if .Values.cassandra.enabled }}
        - name: KONG_CASSANDRA_CONTACT_POINTS
          value: {{ template "kong.cassandra.fullname" . }}
        {{- end }}
        command: [ "/bin/sh", "-c", "kong migrations up" ]
      restartPolicy: OnFailure
{{- end }}
