apiVersion: v1
kind: Service
metadata:
  name: {{ template "kong.fullname" . }}-proxy
  annotations:
    {{- range $key, $value := .Values.proxy.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    app: {{ template "kong.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.proxy.type }}
  loadBalancerIP: 161.117.98.22
  {{- if .Values.proxy.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.proxy.loadBalancerSourceRanges }}
  - {{ $cidr }}
  {{- end }}
  {{- end }}
  externalIPs:
  {{- range $ip := .Values.proxy.externalIPs }}
  - {{ $ip }}
  {{- end }}
  ports:
  {{- if .Values.proxy.http.enabled }}
  - name: kong-proxy
    port: {{ .Values.proxy.http.servicePort }}
    targetPort: {{ .Values.proxy.http.containerPort }}
    nodePort: {{ .Values.proxy.http.nodePort }}
    protocol: TCP
  {{- end }}
  {{- if or .Values.proxy.tls.enabled }}
  - name: kong-proxy-tls
    port: {{ .Values.proxy.tls.servicePort }}
    targetPort: {{ .Values.proxy.tls.containerPort }}
    nodePort: {{ .Values.proxy.tls.nodePort }}
    protocol: TCP
  {{- end }}


  selector:
    app: {{ template "kong.name" . }}
    release: {{ .Release.Name }}
    component: app
