apiVersion: v1
kind: Service
metadata:
  name: {{ template "kong.fullname" . }}-admin
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-t4ng16cntefquy8a7qzpc
  labels:
    app: {{ template "kong.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.admin.type }}
  {{- if eq .Values.admin.type "LoadBalancer" }}
  loadBalancerIP: 161.117.98.22
  {{- if .Values.admin.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.admin.loadBalancerSourceRanges }}
  - {{ $cidr }}
  {{- end }}
  {{- end }}
  {{- end }}
  ports:
  - name: kong-admin
    port: {{ .Values.admin.servicePort }}
    targetPort: {{ .Values.admin.containerPort }}
    nodePort: {{ .Values.admin.nodePort }}
    protocol: TCP
  selector:
    app: {{ template "kong.name" . }}
    release: {{ .Release.Name }}
    component: app
