apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
  labels:
    app: vault
data:
  config.hcl: |-
    storage "mysql" {
      address = "rm-wz9jh6joh13qx2l70.mysql.rds.aliyuncs.com:3306"
      username = "vault"
      password = "UVi1nxaIW3"
      database = "vault"
    }

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }
    ui = true
    disable_mlock = true
    cluster_name = "aixiangdao"