{{- $root := . -}}
{{ $fullname := include "configserver.fullname" . }}
{{ $name := include "configserver.name" . }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: config-server
data:
  bootstrap.yaml: |+
    spring:
      application:
        name: spring-config-server

  application.yaml: |+
    server:
      port: {{ .Values.service.internalPort }}
    management:
      health:
        rabbit:
          enabled: false
      context-path: {{ .Values.management.contextPath }}
      security:
        enabled: {{ .Values.management.security.enabled }}
        role: {{ .Values.management.security.role }}
        
    security:
      user:
        name: {{ .Values.security.user.name }}
        password: {{ .Values.security.user.password }}
    
    spring:
      cloud:
        bus:
          enabled: {{ .Values.spring.cloud.bus.enabled }}
        config:
          server:
            git:
              uri: {{ .Values.spring.cloud.config.server.git.uri }}
{{ if .Values.spring.cloud.config.server.git.searchPaths }}
              searchPaths: {{ .Values.spring.cloud.config.server.git.searchPaths }}
{{ end }}
{{ if .Values.spring.cloud.config.server.git.username }}
              username: {{ .Values.spring.cloud.config.server.git.username }}
{{ end }}
{{ if .Values.spring.cloud.config.server.git.password }}
              password: {{ .Values.spring.cloud.config.server.git.password }}
{{ end }}
{{ template "rabbitMqConfig" . }}

{{ template "eurekaConfig" . }}


