apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: vault
spec:
  secretName: vault
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - vault.aixiangdao.tech
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - vault.aixiangdao.tech
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kiali
spec:
  secretName: kiali
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - kiali.aixiangdao.tech
  acme:
    config:
    - http01:
        ingressClass: none
      domains:
      - kiali.aixiangdao.tech