apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox
  labels:
    app: blackbox
data:
  config.yml: |-
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          valid_status_codes:
          - 200
          - 300
          method: GET
          headers:
            Host: api.aixiangdao.tech
            Accept-Language: en-US
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: false
          fail_if_matches_regexp:
            - "Whitelabel Error Page"
          fail_if_not_matches_regexp:
            - "UP"
          tls_config:
            insecure_skip_verify: true
          preferred_ip_protocol: "ip4"
      http_post_city:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: false
          method: POST
          headers:
            Content-Type: application/json
          body: '{"cityId": 24}'
          tls_config:
            insecure_skip_verify: true
          preferred_ip_protocol: "ip4"   
      http_post_merchant:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: false
          method: POST
          headers:
            Content-Type: application/json
          body: '{"merchantId": 93}'
          tls_config:
            insecure_skip_verify: true
          preferred_ip_protocol: "ip4"   
      http_post_product:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: false
          method: POST
          headers:
            Content-Type: application/json
          body: '{"productId": 142}'
          tls_config:
            insecure_skip_verify: true
          preferred_ip_protocol: "ip4" 
      http_post:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: false
          method: POST
          headers:
            Content-Type: application/json
            userToken: P5Oe3GtKi5ZFcQDRvVHy9N
          body: '{}'
          tls_config:
            insecure_skip_verify: true
          preferred_ip_protocol: "ip4"              
      http_post_AppMerchants:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: false
          method: POST
          headers:
            Content-Type: application/json
            userToken: P5Oe3GtKi5ZFcQDRvVHy9N
          body: '{"cityId":24,"pageIndex":0}'
          tls_config:
            insecure_skip_verify: true
          preferred_ip_protocol: "ip4"
      http_post_getUsers:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: false
          method: POST
          headers:
            Content-Type: application/json
            userToken: P5Oe3GtKi5ZFcQDRvVHy9N
          body: '{"pageIndex":0}'
          tls_config:
            insecure_skip_verify: true
          preferred_ip_protocol: "ip4"
