#
# addon kiali tracing configuration
#
enabled: true
replicaCount: 1
#hub: registry.cn-hangzhou.aliyuncs.com/aliacs-app-catalog
tag: v0.11
ingress:
  enabled: false
  ## Used to create an Ingress record.
  # hosts:
  #  - kiali.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: kiali-tls
    #   hosts:
    #     - kiali.local
dashboard:
  username: admin
  # Default admin passphrase for kiali. Must be set during setup, and
  # changed by overriding the secret
  passphrase: admin

  # Override the automatically detected Grafana URL, usefull when Grafana service has no ExternalIPs
  # grafanaURL:

  # Override the automatically detected Jaeger URL, usefull when Jaeger service has no ExternalIPs
  # jaegerURL:
