#
# mixer configuration
#
image: mixer

env:
  GODEBUG: gctrace=2

istio-policy:
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 5
  cpu:
    targetAverageUtilization: 80

istio-telemetry:
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 5
  cpu:
    targetAverageUtilization: 80

#prometheusStatsdExporter:
#  hub: registry.cn-hangzhou.aliyuncs.com/aliacs-app-catalog
#  tag: v0.6.0
