apiVersion: v1
kind: ConfigMap
metadata:
  name: apollo-config
  labels:
    app: apollo-config
data:
  application-github.properties: |-
    # DataSource
    spring.datasource.url = jdbc:mysql://rm-wz91670r7o0zi042j.mysql.rds.aliyuncs.com:3306/ApolloConfigDB?characterEncoding=utf8
    spring.datasource.username = apollo
    spring.datasource.password = Aixiangdao@Apollo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apollo-portal
  labels:
    app: apollo-portal
data:
  application-github.properties: |-
    # DataSource
    spring.datasource.url = jdbc:mysql://rm-wz91670r7o0zi042j.mysql.rds.aliyuncs.com:3306/ApolloPortalDB?characterEncoding=utf8
    spring.datasource.username = apollo
    spring.datasource.password = Aixiangdao@Apollo