apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "zipkin.fullname" . }}
  labels:
    app: {{ template "zipkin.name" . }}
    chart: {{ template "zipkin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "zipkin.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "zipkin.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "19"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"zipkin"},"name":"zipkin","namespace":"zipkin"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":2,"selector":{"matchLabels":{"app":"zipkin"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"zipkin"}},"spec":{"containers":[{"env":[{"name":"STORAGE_TYPE","value":"elasticsearch"},{"name":"ES_HOSTS","value":"es-cn-v0h0ubx7b0008s9qk.elasticsearch.aliyuncs.com:9200"},{"name":"ES_USERNAME","value":"elastic"},{"name":"ES_PASSWORD","value":"aixiangdao@zipkin1"}],"image":"openzipkin/zipkin","imagePullPolicy":"Always","name":"zipkin","ports":[{"containerPort":9410,"name":"transport","protocol":"TCP"},{"containerPort":9411,"name":"api","protocol":"TCP"}],"resources":{}}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","terminationGracePeriodSeconds":30}}}}
  creationTimestamp: 2018-10-05T06:12:45Z
  generation: 19
  labels:
    app: zipkin
  name: zipkin
  namespace: zipkin
  resourceVersion: "19951730"
  selfLink: /apis/extensions/v1beta1/namespaces/zipkin/deployments/zipkin
  uid: ad26baae-c865-11e8-a7d1-00163e069477
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: zipkin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zipkin
    spec:
      containers:
      - env:
        - name: STORAGE_TYPE
          value: elasticsearch
        - name: ES_HOSTS
          value: http://es-cn-v0h0uiw7w0003807e.public.elasticsearch.aliyuncs.com:9200
        - name: ES_USERNAME
          value: elastic
        - name: ES_PASSWORD
          value: aixiangdao@zipkin1
        - name: ES_HTTP_LOGGING
          value: BASIC
        image: registry-vpc.cn-shenzhen.aliyuncs.com/axd/zipkin:2.11.6
        imagePullPolicy: Always
        name: zipkin
        ports:
        - containerPort: 9410
          name: transport
          protocol: TCP
        - containerPort: 9411
          name: api
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

