enabled: true
replicaCount: 1
image:
  #repository: registry.cn-hangzhou.aliyuncs.com/aliacs-app-catalog/grafana
  tag: 5.2.3
persist: false
storageClassName: "alicloud-disk-efficiency"
accessMode: ReadWriteOnce
storageSize: 20Gi
security:
  enabled: false
  adminUser: admin
  adminPassword: admin
service:
  annotations: {}
  name: http
  type: ClusterIP
  externalPort: 3000
  internalPort: 3000

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      orgId: 1
      url: http://prometheus:9090
      access: proxy
      isDefault: true
      jsonData:
        timeInterval: 5s
      editable: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'istio'
      orgId: 1
      folder: 'istio'
      type: file
      disableDeletion: false
      options:
        path: /var/lib/grafana/dashboards/istio
