apiVersion: v1
kind: Service
metadata:
  name: {{ include "axd-ingressgateway.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "axd-ingressgateway.name" . }}
    helm.sh/chart: {{ include "axd-ingressgateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http2
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: tcp-rabbitmq
      nodePort: 30791
      port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    app.kubernetes.io/name: {{ include "axd-ingressgateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
