# TODO: the original template has service account, roles, etc
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
      annotations:
        sidecar.istio.io/inject: "true"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager
          args:
            - '--config.file=/etc/alertmanager/config.yml'
            - '--storage.path=/alertmanager'
          ports:
            - containerPort: 9093
              name: http
          volumeMounts:
          - mountPath: /etc/alertmanager
            name: config
      volumes:
      - configMap:
          name: alertmanager
        name: config
